const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Behaviors.wrap,
		C3.Plugins.Particles,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.Start_Event1_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Global_Event66_Act1,
		C3.JavaScriptInEvents.Global_Event66_Act2,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Exps.CharacterScale
	];
};
self.C3_JsPropNameTable = [
	{circle1: 0},
	{circle2: 0},
	{Pin: 0},
	{ball: 0},
	{direction: 0},
	{GO: 0},
	{Rotate: 0},
	{ballspeed: 0},
	{Touch: 0},
	{create: 0},
	{Bullet: 0},
	{obstacle: 0},
	{ppositin: 0},
	{Tween: 0},
	{point: 0},
	{pointposition: 0},
	{rate: 0},
	{restart: 0},
	{Audio: 0},
	{OBJECTS: 0},
	{SCORE: 0},
	{Browser: 0},
	{Text: 0},
	{Keyboard: 0},
	{BG2: 0},
	{BG3: 0},
	{BG4: 0},
	{Asset: 0},
	{LocalStorage: 0},
	{Sine: 0},
	{Asset2: 0},
	{Wrap: 0},
	{point2: 0},
	{Asset3: 0},
	{endParticles: 0},
	{SCORE2: 0},
	{pause: 0},
	{back: 0},
	{BG5: 0},
	{AJAX: 0},
	{BG6: 0},
	{restartBAr: 0},
	{menuBG: 0},
	{UI: 0},
	{BG: 0},
	{CREATE: 0},
	{sound: 0},
	{HIGHSCORE: 0},
	{my_id_grep: 0},
	{MY_ID: 0},
	{Date: 0},
	{Time1: 0},
	{Timestamp1: 0},
	{SPEED: 0},
	{mosfet: 0},
	{clickCount: 0},
	{Seconds: 0}
];

self.InstanceType = {
	circle1: class extends self.ISpriteInstance {},
	circle2: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	ballspeed: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	obstacle: class extends self.ISpriteInstance {},
	point: class extends self.ISpriteInstance {},
	pointposition: class extends self.ISpriteInstance {},
	rate: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	SCORE: class extends self.ISpriteFontInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	create: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	BG3: class extends self.ITiledBackgroundInstance {},
	BG4: class extends self.ITiledBackgroundInstance {},
	Asset: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Asset2: class extends self.ISpriteInstance {},
	point2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	endParticles: class extends self.IParticlesInstance {},
	SCORE2: class extends self.ISpriteFontInstance {},
	pause: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	BG5: class extends self.ITiledBackgroundInstance {},
	AJAX: class extends self.IInstance {},
	BG6: class extends self.ITiledBackgroundInstance {},
	restartBAr: class extends self.ISpriteInstance {},
	menuBG: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {}
}